// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Skojjt.Infrastructure.Data;

#nullable disable

namespace Skojjt.Infrastructure.Migrations
{
    [DbContext(typeof(SkojjtDbContext))]
    [Migration("20260412110627_AddTroopCheckinApiKey")]
    partial class AddTroopCheckinApiKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Skojjt.Core.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Skojjt.Core.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<string[]>("PartsAdminLong")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("parts_admin_long");

                    b.PrimitiveCollection<string[]>("PartsAdminShort")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("parts_admin_short");

                    b.PrimitiveCollection<string[]>("PartsScoutLong")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("parts_scout_long");

                    b.PrimitiveCollection<string[]>("PartsScoutShort")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("parts_scout_short");

                    b.Property<int>("ScoutGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("scout_group_id");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ScoutGroupId")
                        .HasDatabaseName("idx_badges_scout_group");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("idx_badges_template");

                    b.HasIndex("ScoutGroupId", "Name")
                        .IsUnique();

                    b.ToTable("badges", (string)null);
                });

            modelBuilder.Entity("Skojjt.Core.Entities.BadgeCompleted", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("BadgeId")
                        .HasColumnType("integer")
                        .HasColumnName("badge_id");

                    b.Property<DateOnly>("CompletedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("completed_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Examiner")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("examiner");

                    b.HasKey("PersonId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("badges_completed", (string)null);
                });

            modelBuilder.Entity("Skojjt.Core.Entities.BadgePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BadgeId")
                        .HasColumnType("integer")
                        .HasColumnName("badge_id");

                    b.Property<int?>("BadgeTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("badge_template_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsAdminPart")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin_part");

                    b.Property<string>("LongDescription")
                        .HasColumnType("text")
                        .HasColumnName("long_description");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("short_description");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId", "SortOrder")
                        .HasDatabaseName("idx_badge_parts_badge_sort");

                    b.HasIndex("BadgeTemplateId", "SortOrder")
                        .HasDatabaseName("idx_badge_parts_template_sort");

                    b.ToTable("badge_parts", null, t =>
                        {
                            t.HasCheckConstraint("ck_badge_parts_owner", "(badge_id IS NOT NULL AND badge_template_id IS NULL) OR (badge_id IS NULL AND badge_template_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Skojjt.Core.Entities.BadgePartDone", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("BadgeId")
                        .HasColumnType("integer")
                        .HasColumnName("badge_id");

                    b.Property<int>("PartIndex")
                        .HasColumnType("integer")
                        .HasColumnName("part_index");

                    b.Property<bool>("IsScoutPart")
                        .HasColumnType("boolean")
                        .HasColumnName("is_scout_part");

                    b.Property<int?>("BadgePartId")
                        .HasColumnType("integer")
                        .HasColumnName("badge_part_id");

                    b.Property<DateOnly>("CompletedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("completed_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ExaminerName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("examiner_name");

                    b.Property<DateTime?>("UndoneAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("undone_at");

                    b.HasKey("PersonId", "BadgeId", "PartIndex", "IsScoutPart");

                    b.HasIndex("BadgeId")
                        .HasDatabaseName("idx_badge_parts_done_badge");

                    b.HasIndex("BadgePartId")
                        .HasDatabaseName("idx_badge_parts_done_badge_part");

                    b.ToTable("badge_parts_done", (string)null);
                });

            modelBuilder.Entity("Skojjt.Core.Entities.BadgeTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<string[]>("PartsAdminLong")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("parts_admin_long");

                    b.PrimitiveCollection<string[]>("PartsAdminShort")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("parts_admin_short");

                    b.PrimitiveCollection<string[]>("PartsScoutLong")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("parts_scout_long");

                    b.PrimitiveCollection<string[]>("PartsScoutShort")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("parts_scout_short");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("badge_templates", (string)null);
                });

            modelBuilder.Entity("Skojjt.Core.Entities.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90)
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsHike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hike");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("location");

                    b.Property<DateOnly>("MeetingDate")
                        .HasColumnType("date")
                        .HasColumnName("meeting_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time without time zone")
                        .HasDefaultValue(new TimeOnly(18, 30, 0))
                        .HasColumnName("start_time");

                    b.Property<int>("TroopId")
                        .HasColumnType("integer")
                        .HasColumnName("troop_id");

                    b.HasKey("Id");

                    b.HasIndex("TroopId", "MeetingDate")
                        .IsUnique()
                        .HasDatabaseName("idx_meetings_troop_date");

                    b.ToTable("meetings", (string)null);
                });

            modelBuilder.Entity("Skojjt.Core.Entities.MeetingAttendance", b =>
                {
                    b.Property<int>("MeetingId")
                        .HasColumnType("int")
                        .HasColumnName("meeting_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.HasKey("MeetingId", "PersonId");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_meeting_attendances_person");

                    b.ToTable("meeting_attendances", (string)null);
                });

            modelBuilder.Entity("Skojjt.Core.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("AltEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alt_email");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DadEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dad_email");

                    b.Property<string>("DadMobile")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dad_mobile");

                    b.Property<string>("DadName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dad_name");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.PrimitiveCollection<int[]>("MemberYears")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("member_years");

                    b.Property<string>("Mobile")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mobile");

                    b.Property<string>("MumEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mum_email");

                    b.Property<string>("MumMobile")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mum_mobile");

                    b.Property<string>("MumName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("mum_name");

                    b.Property<string>("PersonalNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("personal_number");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("phone");

                    b.Property<bool>("Removed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("removed");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("street");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zip_code");

                    b.Property<string>("ZipName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("zip_name");

                    b.HasKey("Id");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("Skojjt.Core.Entities.ScoutGroup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address");

                    b.Property<string>("ApiKeyAllMembers")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("api_key_all_members");

                    b.Property<string>("ApiKeyUpdateMembership")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("api_key_update_membership");

                    b.Property<string>("ApiKeyWaitinglist")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("api_key_waitinglist");

                    b.Property<string>("AssociationId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("association_id");

                    b.Property<bool>("AttendanceInclHike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("attendance_incl_hike");

                    b.Property<int>("AttendanceMinSemester")
                        .HasColumnType("integer");

                    b.Property<int>("AttendanceMinYear")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("attendance_min_year");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bank_account");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DefaultCampLocation")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("default_camp_location");

                    b.Property<string>("DefaultMeetingLocation")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("default_meeting_location");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("MunicipalityId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("municipality_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("NextLocalTroopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(250)
                        .HasColumnName("next_local_troop_id");

                    b.Property<string>("OrganisationNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("organisation_number");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("postal_address");

                    b.Property<string>("Signatory")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("signatory");

                    b.Property<string>("SignatoryEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("signatory_email");

                    b.Property<string>("SignatoryPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("signatory_phone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("scout_groups", (string)null);
                });

            modelBuilder.Entity("Skojjt.Core.Entities.ScoutGroupPerson", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("ScoutGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("scout_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("GroupRoles")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("group_roles");

                    b.Property<bool>("NotInScoutnet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("not_in_scoutnet");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("PersonId", "ScoutGroupId");

                    b.HasIndex("NotInScoutnet")
                        .HasDatabaseName("idx_scout_group_persons_not_in_scoutnet");

                    b.HasIndex("ScoutGroupId")
                        .HasDatabaseName("idx_scout_group_persons_group");

                    b.ToTable("scout_group_persons", (string)null);
                });

            modelBuilder.Entity("Skojjt.Core.Entities.Semester", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("IsAutumn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_autumn");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("semesters", null, t =>
                        {
                            t.HasCheckConstraint("chk_semester_id", "id = (year * 10) + CASE WHEN is_autumn THEN 1 ELSE 0 END");
                        });
                });

            modelBuilder.Entity("Skojjt.Core.Entities.Troop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("CampEndDate")
                        .HasColumnType("date")
                        .HasColumnName("camp_end_date");

                    b.Property<DateOnly?>("CampStartDate")
                        .HasColumnType("date")
                        .HasColumnName("camp_start_date");

                    b.Property<int>("DefaultDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90)
                        .HasColumnName("default_duration_minutes");

                    b.Property<string>("DefaultMeetingLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("default_meeting_location");

                    b.Property<TimeOnly>("DefaultStartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time without time zone")
                        .HasDefaultValue(new TimeOnly(18, 30, 0))
                        .HasColumnName("default_start_time");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("ScoutGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("scout_group_id");

                    b.Property<string>("ScoutnetCheckinApiKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scoutnet_checkin_api_key");

                    b.Property<int>("ScoutnetId")
                        .HasColumnType("integer")
                        .HasColumnName("scoutnet_id");

                    b.Property<int?>("ScoutnetProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("scoutnet_project_id");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer")
                        .HasColumnName("semester_id");

                    b.Property<int>("TroopType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("troop_type");

                    b.Property<int?>("UnitTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_type_id");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.HasIndex("ScoutGroupId", "SemesterId")
                        .HasDatabaseName("idx_troops_scout_group_semester");

                    b.HasIndex("ScoutnetId", "ScoutGroupId", "SemesterId")
                        .IsUnique()
                        .HasDatabaseName("idx_troops_natural_key");

                    b.ToTable("troops", (string)null);
                });

            modelBuilder.Entity("Skojjt.Core.Entities.TroopBadge", b =>
                {
                    b.Property<int>("TroopId")
                        .HasColumnType("integer")
                        .HasColumnName("troop_id");

                    b.Property<int>("BadgeId")
                        .HasColumnType("integer")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("TroopId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("troop_badges", (string)null);
                });

            modelBuilder.Entity("Skojjt.Core.Entities.TroopPerson", b =>
                {
                    b.Property<int>("TroopId")
                        .HasColumnType("integer")
                        .HasColumnName("troop_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsLeader")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_leader");

                    b.Property<string>("Patrol")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("patrol");

                    b.Property<int?>("PatrolId")
                        .HasColumnType("integer")
                        .HasColumnName("patrol_id");

                    b.HasKey("TroopId", "PersonId");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_troop_persons_person");

                    b.ToTable("troop_persons", (string)null);
                });

            modelBuilder.Entity("Skojjt.Core.Entities.Badge", b =>
                {
                    b.HasOne("Skojjt.Core.Entities.ScoutGroup", "ScoutGroup")
                        .WithMany("Badges")
                        .HasForeignKey("ScoutGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skojjt.Core.Entities.BadgeTemplate", "Template")
                        .WithMany("Badges")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ScoutGroup");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Skojjt.Core.Entities.BadgeCompleted", b =>
                {
                    b.HasOne("Skojjt.Core.Entities.Badge", "Badge")
                        .WithMany("Completed")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skojjt.Core.Entities.Person", "Person")
                        .WithMany("BadgesCompleted")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Skojjt.Core.Entities.BadgePart", b =>
                {
                    b.HasOne("Skojjt.Core.Entities.Badge", "Badge")
                        .WithMany("Parts")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Skojjt.Core.Entities.BadgeTemplate", "BadgeTemplate")
                        .WithMany("Parts")
                        .HasForeignKey("BadgeTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Badge");

                    b.Navigation("BadgeTemplate");
                });

            modelBuilder.Entity("Skojjt.Core.Entities.BadgePartDone", b =>
                {
                    b.HasOne("Skojjt.Core.Entities.Badge", "Badge")
                        .WithMany("PartsDone")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skojjt.Core.Entities.BadgePart", "BadgePart")
                        .WithMany("PartsDone")
                        .HasForeignKey("BadgePartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Skojjt.Core.Entities.Person", "Person")
                        .WithMany("BadgePartsDone")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("BadgePart");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Skojjt.Core.Entities.Meeting", b =>
                {
                    b.HasOne("Skojjt.Core.Entities.Troop", "Troop")
                        .WithMany("Meetings")
                        .HasForeignKey("TroopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Troop");
                });

            modelBuilder.Entity("Skojjt.Core.Entities.MeetingAttendance", b =>
                {
                    b.HasOne("Skojjt.Core.Entities.Meeting", "Meeting")
                        .WithMany("Attendances")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skojjt.Core.Entities.Person", "Person")
                        .WithMany("MeetingAttendances")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Skojjt.Core.Entities.ScoutGroupPerson", b =>
                {
                    b.HasOne("Skojjt.Core.Entities.Person", "Person")
                        .WithMany("ScoutGroupPersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skojjt.Core.Entities.ScoutGroup", "ScoutGroup")
                        .WithMany("ScoutGroupPersons")
                        .HasForeignKey("ScoutGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("ScoutGroup");
                });

            modelBuilder.Entity("Skojjt.Core.Entities.Troop", b =>
                {
                    b.HasOne("Skojjt.Core.Entities.ScoutGroup", "ScoutGroup")
                        .WithMany("Troops")
                        .HasForeignKey("ScoutGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skojjt.Core.Entities.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoutGroup");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Skojjt.Core.Entities.TroopBadge", b =>
                {
                    b.HasOne("Skojjt.Core.Entities.Badge", "Badge")
                        .WithMany("TroopBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skojjt.Core.Entities.Troop", "Troop")
                        .WithMany("TroopBadges")
                        .HasForeignKey("TroopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Troop");
                });

            modelBuilder.Entity("Skojjt.Core.Entities.TroopPerson", b =>
                {
                    b.HasOne("Skojjt.Core.Entities.Person", "Person")
                        .WithMany("TroopPersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skojjt.Core.Entities.Troop", "Troop")
                        .WithMany("TroopPersons")
                        .HasForeignKey("TroopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Troop");
                });

            modelBuilder.Entity("Skojjt.Core.Entities.Badge", b =>
                {
                    b.Navigation("Completed");

                    b.Navigation("Parts");

                    b.Navigation("PartsDone");

                    b.Navigation("TroopBadges");
                });

            modelBuilder.Entity("Skojjt.Core.Entities.BadgePart", b =>
                {
                    b.Navigation("PartsDone");
                });

            modelBuilder.Entity("Skojjt.Core.Entities.BadgeTemplate", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Skojjt.Core.Entities.Meeting", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("Skojjt.Core.Entities.Person", b =>
                {
                    b.Navigation("BadgePartsDone");

                    b.Navigation("BadgesCompleted");

                    b.Navigation("MeetingAttendances");

                    b.Navigation("ScoutGroupPersons");

                    b.Navigation("TroopPersons");
                });

            modelBuilder.Entity("Skojjt.Core.Entities.ScoutGroup", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("ScoutGroupPersons");

                    b.Navigation("Troops");
                });

            modelBuilder.Entity("Skojjt.Core.Entities.Troop", b =>
                {
                    b.Navigation("Meetings");

                    b.Navigation("TroopBadges");

                    b.Navigation("TroopPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
